'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Oversight.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property account12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property account24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("account24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addressbook12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addressbook12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addressbook24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addressbook24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property asset12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asset12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property asset24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("asset24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assetFinance12x11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assetFinance12x11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assetFinance24x21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assetFinance24x21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assetLending12x11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assetLending12x11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assetLending24x21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assetLending24x21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assetmgt12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assetmgt12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property assetmgt24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("assetmgt24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property attachments12x13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attachments12x13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property attachments24x27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("attachments24x27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bank12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bank12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bank24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bank24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boxes12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boxes12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boxes24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boxes24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boxShot12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boxShot12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property boxShot24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boxShot24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bricks12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bricks12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bricks24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bricks24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property businessInsurance12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("businessInsurance12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property businessInsurance24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("businessInsurance24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancel24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancel24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property check24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("check24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clients12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clients12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property clients24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clients24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property config12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("config12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property config24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("config24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property configb12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configb12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property configb24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("configb24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copyright12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copyright12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property copyright24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("copyright24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property creditcard12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creditcard12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property creditcard24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("creditcard24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property db12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property db24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("db24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property delete24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("delete24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property docs12x14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("docs12x14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property docs24x27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("docs24x27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property down24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("down24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property download24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property duplicate12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("duplicate12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property duplicate24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("duplicate24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property empresa12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("empresa12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property empresa24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("empresa24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excel12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excel24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excel24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property expenses12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expenses12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property expenses24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("expenses24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property explosion12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explosion12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property explosion24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("explosion24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property files12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("files12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property files24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("files24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folders12x14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folders12x14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property folders24x27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folders24x27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gas12x11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gas12x11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gas24x22() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gas24x22", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gem12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gem12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gem24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gem24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property govermentSchemes12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("govermentSchemes12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property govermentSchemes24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("govermentSchemes24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hammer12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammer12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hammer24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("hammer24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heart12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property heart24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("heart24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property helmet12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("helmet12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property helmet24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("helmet24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property idea15x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("idea15x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property idea8x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("idea8x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property image24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property income12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("income12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property income24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("income24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property insertcard12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insertcard12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property insertcard24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("insertcard24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inventory_2_12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inventory_2_12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property inventory_2_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inventory_2_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoiceFinance12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoiceFinance12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property invoiceFinance24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("invoiceFinance24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key_2_12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_2_12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key_2_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key_2_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property key24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("key24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property licence12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("licence12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property licence24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("licence24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property list24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("list24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property material12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("material12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property material24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("material24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property message12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("message12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property message24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("message24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property money24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("money24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newcard12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newcard12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property newcard24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newcard24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property next24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("next24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property note24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("note24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property open24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("open24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property package12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property package24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("package24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paperclip12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paperclip12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property paperclip24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paperclip24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payment12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payment24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payment24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payrollSolutions12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payrollSolutions12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property payrollSolutions24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("payrollSolutions24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property percent12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("percent12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property percent24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("percent24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phone12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property phone24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("phone24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pin12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pin12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property pin24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pin24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property police12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("police12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property police24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("police24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property powerpnt12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerpnt12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property powerpnt24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("powerpnt24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property previous12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property previous24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property project_2_12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("project_2_12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property project_2_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("project_2_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property project12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("project12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property project24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("project24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property propertyFinance12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("propertyFinance12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property propertyFinance24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("propertyFinance24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property question12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property question24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quotation12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quotation12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property quotation24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("quotation24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relationships12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relationships12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relationships24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relationships24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property report24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("report24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reset12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property reset24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("reset24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property save24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("save24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveclose17x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveclose17x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property saveclose33x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("saveclose33x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scaleRuler12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scaleRuler12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scaleRuler24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scaleRuler24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scheduler12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scheduler12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scheduler24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scheduler24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property search24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("search24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property speed12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speed12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property speed24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speed24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stockFinance12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stockFinance12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property stockFinance24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("stockFinance24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tag12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tag24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tasks12x13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tasks12x13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tasks24x27() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tasks24x27", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property thundera() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("thundera", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property thundera128x128() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("thundera128x128", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property truck12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("truck12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property truck24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("truck24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property truckb12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("truckb12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property truckb24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("truckb24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unit12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unit12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property unit24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("unit24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property up24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("up24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property user24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property winmineVista16x16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("winmineVista16x16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property winmineVista32x32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("winmineVista32x32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property winmineVista48x48() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("winmineVista48x48", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property winmineXP16x16() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("winmineXP16x16", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property winmineXP32x32() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("winmineXP32x32", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property winmineXP48x48() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("winmineXP48x48", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property word12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property word24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("word24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property worker12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("worker12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property worker24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("worker24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yes_2_12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yes_2_12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yes_2_24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yes_2_24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yes12x12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yes12x12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property yes24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("yes24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
